apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-pod
          image: us-central1-docker.pkg.dev/norse-block-420814/google-repo/restful-api:v1
          imagePullPolicy: Always
  replicas: 3
  selector:
    matchLabels:
      app: my-app
