apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
    spec:
      containers:
        - name: my-pod
          image: sherry50430/jib_repo:latest
          ports:
            - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      type: my-app
