# workflow 名稱
name: Java CI with Maven

# 什麼情況下觸發 workflow
on:
  # main branch 有 push 時觸發 workflow 
  push:
    branches: [ "main" ]
  # main branch 有 Pull Request 時觸發 workflow 
  pull_request:
    branches: [ "main" ]

# Job 可以循序或平行執行
jobs:
  # 這個 workflow 只有一個 job，名稱為 "build"
  build:
    # 在作業系統為 ubuntu 的 runner 執行這個 job
    runs-on: ubuntu-latest
    # Steps 會循序執行
    steps:
      # $GITHUB_WORKSPACE 下簽出您的存儲庫，以便您的工作可以訪問它
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn compile jib:build -Ddocker.username=sherry50430 -Ddocker.password=s89917629
      - name: deploy
        run: echo "deploy...."
